FROM python:3.9

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy application files
COPY exporter.py .

# Run the exporter
CMD ["python", "exporter.py"]
